export const GET_STOCK_REQUEST = "GET_STOCK_REQUEST";
export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS";
export const GET_STOCK_FAILURE = "GET_STOCK_FAILURE";

export const POST_STOCK_REQUEST = "POST_STOCK_REQUEST";
export const POST_STOCK_SUCCESS = "POST_STOCK_SUCCESS";
export const POST_STOCK_FAILURE = "POST_STOCK_FAILURE";

export const UPDATE_STOCK_REQUEST = "UPDATE_STOCK_REQUEST";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const UPDATE_STOCK_FAILURE = "UPDATE_STOCK_FAILURE";

export const DELETE_STOCK_REQUEST = "DELETE_STOCK_REQUEST";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAILURE = "DELETE_STOCK_FAILURE";
